thttp:
  host: "0.0.0.0"
  port: "9090"
http:
  host: "0.0.0.0"
  port: "8081"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  username: "mule"
  password: "mule"
  database: "training"
  